version: 0.4.{build}

platform:
  - x64

environment:
  JSPM_GITHUB_AUTH_TOKEN:
    secure: DjDHKWLd+lqIDf84qOaG1PjZ+uILUomO+LKwm8bfDECXdrV/wdbn7vRxAF8EEsfk

cache:
  - node_modules
  - jspm_packages
  - '%USERPROFILE%\.electron'
  - '%LOCALAPPDATA%\Yarn'
  - '%LOCALAPPDATA%\.jspm'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 7.4.0 x64
  - choco install -i yarn
  - git reset --hard HEAD
  - yarn
  - node_modules\.bin\jspm config registries.github.timeouts.lookup 180
  - node_modules\.bin\jspm config registries.npm.timeouts.lookup 180
  - node_modules\.bin\jspm install

build_script:
  - node_modules\.bin\gulp build --production
  - node_modules\.bin\electron-packager . --platform=win32 --app-version %APPVEYOR_BUILD_VERSION% --build-version %APPVEYOR_BUILD_VERSION% --asar=true --electron-version 1.4.12
  - REN swimming-win32-x64 swimming-%APPVEYOR_BUILD_VERSION%-win32-x64

test: off

artifacts:
  - path: swimming-%APPVEYOR_BUILD_VERSION%-win32-x64
