version: 0.4.{build}

platform:
  - x64

environment:
  JSPM_GITHUB_AUTH_TOKEN:
    secure: DjDHKWLd+lqIDf84qOaG1PjZ+uILUomO+LKwm8bfDECXdrV/wdbn7vRxAF8EEsfk

cache:
  - node_modules
  - jspm_packages
  - '%USERPROFILE%\.electron'
  - '%LOCALAPPDATA%\Yarn'
  - '%LOCALAPPDATA%\.jspm'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 7.4.0 x64
  - choco install -i yarn
  - git reset --hard HEAD
  - yarn global bin
  - SET YARN_GLOBAL_BIN=(yarn global bin)
  - "%YARN_GLOBAL_BIN%"
  - SET PATH=%YARN_GLOBAL_BIN%;%PATH%
  - yarn
  - yarn global add electron-packager
  - node_modules\.bin\jspm config registries.github.timeouts.lookup 180
  - node_modules\.bin\jspm config registries.npm.timeouts.lookup 180
  - node_modules\.bin\jspm install

build_script:
  # - node --version
  - node_modules\.bin\gulp build --production
  - npm prune
  - electron-packager . --platform=win32

test: off

artifacts:
  - path: swimming.web-win32-x64
    name: app
